checking notify stage

diff --git a/.gitlab/ci/cypress-testing.gitlab-ci.yml b/.gitlab/ci/cypress-testing.gitlab-ci.yml
--- a/.gitlab/ci/cypress-testing.gitlab-ci.yml
+++ b/.gitlab/ci/cypress-testing.gitlab-ci.yml
@@ -1,10 +1,24 @@
 .cypress_testing:
   stage: cypress-testing
   image: cypress/browsers:node-22.11.0-chrome-130.0.6723.69-1-ff-132.0-edge-130.0.2849.56-1
-  script: 
+  script:
+    - echo "Cloning repository..."
     - git clone https://oauth2:${OAUTH_GITLAB_TOKEN}@${REPOSITORY_URL}
     - WORKDIR=$(echo ${REPOSITORY_URL} | sed 's#.*/\([^/]*\)\.git#\1#')
     - cd ${WORKDIR} && git checkout ${GIT_BRANCH}
+    - echo "Running Cypress tests..."
     - bash run.sh
-    - TEST_STATUS=$?
-    - echo $TEST_STATUS
+    - TEST_STATUS=$?  # Capture the exit status of the Cypress tests
+  after_script:
+    - echo "Cypress test finished"
+    - |
+      if [ "$TEST_STATUS" -eq 0 ]; then
+        MESSAGE="Cypress tests succeeded in project: ${CI_PROJECT_NAME}."
+      else
+        MESSAGE="Cypress tests failed in project: ${CI_PROJECT_NAME}."
+      fi
+
+    # Send the message via Telegram
+    - curl -X POST "https://api.telegram.org/bot${TELEGRAM_BOT_TOKEN}/sendMessage" \
+          -d "chat_id=${TELEGRAM_CHAT_ID}" \
+          -d "text=${MESSAGE}"
